### ISSUE TITLE
Create a "Zen Mode" for the text editor

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#1]
Quiet-Text is a Python text editor made with tkinter. Right now there is a "Quiet Mode" tab in the text editor's menu, but it doesn't currently do anything. The idea is that when you push the "Quiet Mode" button, it hides the menu bar and the status bar from the user's view. The only thing that should be visible is the text area of the application. I want this to function similar to Visual Studio Code's "Zen Mode" (as stated in the title).

**Comment by Ryuno-Ki** [comment]
For reference: https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_zen-mode

Leaving with <kbd>Esc</kbd>?

**Comment by SethWalkeroo** [comment]
> For reference: https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_zen-mode
> 
> Leaving with Esc?

Oh good idea to link it. Thank you. Yes, exit with <kbd>Esc</kbd>. Basically a clone of that feature in VS Code.
