### ISSUE TITLE
Add comments to explain existing code

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#10]
This isn't too important, but it would be great to have comments explaining the code for new contributors. I will try to work on this in my spare time.

**Comment by aishuo07** [comment]
Can i work on this

**Comment by SethWalkeroo** [comment]
@aish0007 sure, if you want to, but the code is up to change and a lot of things may change down the line.

**Comment by aishuo07** [comment]
okay then i will add comments as soon as something is added every time is that okay

**Comment by SethWalkeroo** [comment]
@aish0007 Sure, if you can comment everything accurately. It might be better if I just comment the code myself, but if you're down for actually reading and understanding things, you can go for it.

**Comment by aishuo07** [comment]
okay then assign me this task

**Comment by aishuo07** [comment]
i have created a pull request please review
