### ISSUE TITLE
Improve settings.json to adjust more features in the editor. 

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#11]
Right now settings.json only effects the font, background color, and text color of the editor. It would be really cool for it to adjust things like line height and menu colors as well

**Comment by JuliusChrona** [comment]
@SethWalkeroo Hello, i want to do it. Can you assign me? ^_^

**Comment by SethWalkeroo** [comment]
@JuliusChrona For sure! Message me if you need help with anything.

**Comment by JuliusChrona** [comment]
Ok, i made line height

**Comment by SethWalkeroo** [comment]
@JuliusChrona Ok, make a pull request so I can review your change and merge it with the main branch.
