### ISSUE TITLE
Create tabs that allow for multiple windows in the text editor.

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#14]
Right now you can only have one document open at a time, and that greatly inhibits productivity. The goal is to create tabs that allows a user to switch between multiple opened documents.

**Comment by kishore-tw** [comment]
I would like to work on this. Can you assign this issue to me?

**Comment by Kishore-abhimanyu** [comment]
I would like to work on this. Can you assign me this issue?

**Comment by SethWalkeroo** [comment]
@Kishore-abhimanyu Awesome! Assigned to you.
