### ISSUE TITLE
Allow user's to change the font size with CTRL and scroll-wheel.

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#16]
This is one of my favorite features in both Atom and Sublime text. It would be awesome to have a simple and easy way to change the font size.

**Comment by tdserapio** [comment]
Although I still need to research some parts of this, may I be assigned? Thank you very much! This is also really interesting...

**Comment by SethWalkeroo** [comment]
@tdserapio Sure, give it a shot. This would be really great! Reach out if you have questions about anything.

**Comment by tdserapio** [comment]
Thank you so much @SethWalkeroo !

**Comment by tdserapio** [comment]
One question @SethWalkeroo , what is the maximum font size?

**Comment by SethWalkeroo** [comment]
@tdserapio I don't believe there is one. Does there need to be?

**Comment by tdserapio** [comment]
Oh, because sometimes, when you scroll too much, it will get so big that it probably would not fit anymore.

**Comment by SethWalkeroo** [comment]
@tdserapio I think it's fine for that to happen as long as it doesn't break the program in some way.

**Comment by tdserapio** [comment]
Is there already some code for font_size or may I make it myself?

**Comment by SethWalkeroo** [comment]
There is a setting called 'font_size' that is used to configure 'self.font_style' in the text area. Besides that, I don't believe there is any  sort of functionality/code to control the font size. You can whatever you need to and we can make improvements if necessary. I apologize for there is a messy mixture of hard coded features and variables at the moment. I really just wanted to get things working before I focused on quality of life features and customization.

**Comment by tdserapio** [comment]
Thank you for the information. Much appreciated

**Comment by tdserapio** [comment]
I have some bad news. So, I have a lot of things to do right now, so is it okay if this may be assigned to another willing person?

**Comment by sumasreeeduru** [comment]
Can you assign me?

**Comment by Thanarathanam** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by SethWalkeroo** [comment]
@tdserapio Of course, do what you need to do.

**Comment by SethWalkeroo** [comment]
@Thanarathanam Yep, assigned to you.
