### ISSUE TITLE
Running a file in Windows machine doesn't run the code.

### ISSUE THREAD

**Issue by erzaliator** [SethWalkeroo/Quiet-Text#20]
**Describe the bug**
If you have Quiet-Text in installed in a Windows machine, running a py file (Ctrl+b), issues the gnome-terminal command causing it to not execute.

**To Reproduce**
1. Open your python file.
2. Press Ctrl+b.
3. See the cmd terminal for error.

**Expected behavior**
The code should instead run a child cmd terminal and execute the python command there.

**Screenshots**
![image](https://user-images.githubusercontent.com/5917670/95342418-0af7cb80-08d5-11eb-9980-a56da99b7c91.png)

**Operating system :**
 - Windows 10
 
 **Additional context**
A simple fix would be to check the operating system and run separate commands.

**Comment by erzaliator** [comment]
I already have a tested solution in place, could you please assign me the issue? @SethWalkeroo

**Comment by SethWalkeroo** [comment]
@erzaliator Ah, thanks for testing this. You can make the changes for it to work on your system, but the main issue is that there are many different terminal applications out there and i'm not sure if we can handle for all of them. The ultimate solution would be to create an integrated terminal for the text editor, but that would be quite difficult. I have assigned this issue to you, but it is a much bigger problem than you might think.

**Comment by erzaliator** [comment]
> but the main issue is that there are many different terminal applications out there and I'm not sure if we can handle for all of them.

That shouldn't be an issue. For Linux gnome is fairly common and my implementation for Windows support uses the basic command line terminal which comes default.

**Comment by erzaliator** [comment]
If I may blatantly request, can the necessary tags Hacktoberfest be added as well :)

**Comment by SethWalkeroo** [comment]
@erzaliator Yeah, i'll get on that.
