### ISSUE TITLE
Make it so the scroll bar doesn't work when resizing the font with CTRL + MouseWheel

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#23]
We just implemented font resizing with ctrl and mouse wheel but it still scrolls the screen while you resize the text. This is bad for long documents when you want to increase the text size but not scroll to the bottom at the same time.

**Comment by Sid200026** [comment]
I can work on this

**Comment by SethWalkeroo** [comment]
@Sid200026 Cool! Assigned to you.

**Comment by i5han2** [comment]
I have worked on a similar functionality. please assign me this, i can solve this issue
