### ISSUE TITLE
Create key binding documentation for the readme

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#24]
This should be pretty. Add a section to the readme that displays all of the keybindings for the text editor. 

E.G.    <kbd>ctrl</kbd> + <kbd>c</kbd> | Copy

**Comment by thainapires** [comment]
Hi @SethWalkeroo ! I would like to do this task. Could you assign it to me? 😃

**Comment by SethWalkeroo** [comment]
@thainapires Sure!
