### ISSUE TITLE
Add the ability to bold and highlight text when working in text files

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#27]
This feature is for note taking and should only work in .txt files.

**Comment by punidramesh** [comment]
Hi, I would like to attempt to fix this issue.

**Comment by SethWalkeroo** [comment]
@punidramesh Sure give it a shot. Assigned to you.

**Comment by punidramesh** [comment]
I noticed that 'Ctrl + B' is assigned to 'Run file'. Can that be assigned to 'Ctrl + R' or anything other key-binding ? It would make more sense to use 'Ctrl + B' for making the text bold.

**Comment by SethWalkeroo** [comment]
@punidramesh Yeah, you can rebind that. The run function only works on gnome terminals right now, so it is basically non functional anyway.
