### ISSUE TITLE
Allow users to highlight text in different colors

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#49]
Right now you can highlight text in the editor, but all the text has to be highlighting in the same color. This sucks and it would be great to be able to highlight different text in different colors. Below is an example of three different highlights that were supposed to have different colors, but did not.

![Image of Yaktocat](https://raw.githubusercontent.com/SethWalkeroo/Quiet-Text/main/images/highbug.png)

**Comment by AlejandroGomezFrieiro** [comment]
This project looks interesting, always wanted to work on a text editor in Python. Can I work on this issue?

**Comment by SethWalkeroo** [comment]
> This project looks interesting, always wanted to work on a text editor in Python. Can I work on this issue?

Thanks for showing interest. I love a good text editor and I really wanted to create one of my own. I'm not sure how good I can make this one using only Python, but i'd love to find out. You are welcome to work on any of the existing issues, or create a new issue/feature you would like to fix/add.
