### ISSUE TITLE
"Toggle Line Numbers" option in View cascade for turning on/off the line numbers visibility

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#53]
It would also be great to have a key binding associated as well.

**Comment by Kishore-abhimanyu** [comment]
I can take this to hide line numbers by key binding. is that okay?

**Comment by SethWalkeroo** [comment]
@hrishikesharma You can work on this, but I would really prefer it if you finish the other issues you are working on first. If you don't plan on finishing the other issues, it's fine, just tell me so I know whether or not to work on them myself.

**Comment by hrishikesharma** [comment]
> @hrishikesharma You can work on this, but I would really prefer it if you finish the other issues you are working on first. If you don't plan on finishing the other issues, it's fine, just tell me so I know whether or not to work on them myself.

currently I am not working on any other issue so maybe I can give it a try.

**Comment by SethWalkeroo** [comment]
@hrishikesharma I apologize, I was busy and I thought you were somebody else. Disregard what i said in the previous comment.

**Comment by hrishikesharma** [comment]
couldn't do it so unassigning me. So sorry, I really need some more skills to do object-oriented programming.

**Comment by hrishikesharma** [comment]
Btw there is an error in line no. 480 on https://github.com/SethWalkeroo/Quiet-Text/blob/main/src/quiet_app_launch.py

it should be quoteright , not apostrophe

**Comment by SethWalkeroo** [comment]
@hrishikesharma Huh, that's interesting. Apostrophe worked for me, but so does quoteright. Are you on Windows? I'm guessing apostrophe might be a Linux thing or something. Anyways, thanks for trying. I've already thought of a way to solve this, so it's no problem.

**Comment by hrishikesharma** [comment]
> @hrishikesharma Huh, that's interesting. Apostrophe worked for me, but so does quoteright. Are you on Windows? I'm guessing apostrophe might be a Linux thing or something. Anyways, thanks for trying. I've already thought of a way to solve this, so it's no problem. 

Yes brother , I am using windows

**Comment by FilipZajdel** [comment]
Hello, what about "Toggle Line Numbers" option in _View_ cascade for turning on/off the line numbers visibility?

**Comment by SethWalkeroo** [comment]
@FilipZajdel That's a much better name for the issue :+1:

**Comment by FilipZajdel** [comment]
Can I work on this one? 
Will _[Ctrl-Shift-L]_ key binding suitable for this function?

**Comment by SethWalkeroo** [comment]
@FilipZajdel sure, go ahead.

**Comment by jeffmikels** [comment]
I'm sorry I missed seeing that you assigned it already. I have a finished solution if @FilipZajdel doesn't get it or if you want to accept both our pull requests.
