### ISSUE TITLE
Create an autoclosing parenthesis and autoclosing brackets feature 

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#54]
This would be a great start for quality of life improvements in the editor.

**Comment by Kishore-abhimanyu** [comment]
I would like to work on this? Can you assign me?

**Comment by Kishore-abhimanyu** [comment]
I like to work on this and i started working on this. Can you assign me?

**Comment by Kishore-abhimanyu** [comment]
Can you assign the issue so that i can fix it?

**Comment by Kishore-abhimanyu** [comment]
why is it not merged?can i know the issue?
