### ISSUE TITLE
Create an auto indent feature for the text editor

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#58]
Allow the editor to automatically indent after the beginning of a block.

**Comment by Kishore-abhimanyu** [comment]
i can take this if you assign me

**Comment by SethWalkeroo** [comment]
@Kishore-abhimanyu You can do this, but I would like you to re implement the auto closing parenthesis and brackets on the current branch. I also need you to change the key bindings to bindings compatible on the list. I apologize for the previous pull request because I didn't inform you what I was asking for as well as I could have, and I sent a broken link.' <Shift-{>' **is not a valid binding**. You need to use <kbd>Shift</kbd>+<kbd>bracketleft</kbd> as listed here: https://www.tcl.tk/man/tcl8.4/TkCmd/keysyms.htm

Create another pull request after the changes are made and I will be sure to merge it and give you the hacktoberfest label if that's something you care about.
