### ISSUE TITLE
Create a pop up message that asks the user if they want to save before exiting.

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#6]
The pop up should either instantly save the file if it already exists, or allow the user to do the "save as" function if it has never been saved before.

**Comment by JanhaviDahihande** [comment]
Hey @SethWalkeroo I would like to take up this issue!

**Comment by SethWalkeroo** [comment]
@JanhaviDahihande Awesome! Go for it, assigned to you. Reach out to me if you have any questions about the code, I am aware there aren't any comments yet and it might be hard to read.

**Comment by Ryuno-Ki** [comment]
@Ryuno-Ki is now known as @JanhaviDahihande :-D

**Comment by SethWalkeroo** [comment]
> @Ryuno-Ki is now known as @JanhaviDahihande :-D

Well that's embarrassing. Woops!

**Comment by hrishikesharma** [comment]
can i give it a try?

**Comment by aishuo07** [comment]
Is this open to work upon or it is completed

**Comment by SethWalkeroo** [comment]
@aish0007 This is open. It is assigned, but i'll except a pull request if you have a solution.

**Comment by aishuo07** [comment]
Okay thanks

**Comment by aishuo07** [comment]
I created a pull request please review it

**Comment by aishuo07** [comment]
please add HackOctober accepted tag

**Comment by Ryuno-Ki** [comment]
If you add `refs #6` to the commit message GitHub will link https://github.com/SethWalkeroo/Quiet-Text/pull/26 to this issue.

You can even [close an issue via commit message](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) once the associated PR gets merged!
