### ISSUE TITLE
Changing font size with scroll wheel resets settings.yaml back to default

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#61]
I don't know why this is happening, but the settings get reset to their default values when a user changes the font size with scroll wheel.

**Comment by FilipZajdel** [comment]
Hi, can I work on this one? 

I suppose that the function _load_settings_data_ in quiet_app_launch.py:395 is called with wrong argument.

**Comment by SethWalkeroo** [comment]
@FilipZajdel Sure, assigned to you!
