### ISSUE TITLE
Restyle the  ctrl+f "find and replace" feature for the text editor

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#65]
Restyle the find and replace feature located in **quiet_find.py** to be more visually appealing and in tune with the rest of the editor's theme.

**Comment by jianajavier** [comment]
@SethWalkeroo I can take this on, can you assign to me please?

**Comment by jianajavier** [comment]
PR for this issue is here: https://github.com/SethWalkeroo/Quiet-Text/pull/87
