### ISSUE TITLE
Enhance the auto indentation feature to indent all the code beneath a block

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#71]
Right now there is an autoindentation function, but it only works for one line after a colon ":". It would be nice to have everything under the block be indented as well.

**Comment by jianajavier** [comment]
@SethWalkeroo I can try to take this on. Can you assign to me please?

**Comment by SethWalkeroo** [comment]
> @SethWalkeroo I can try to take this on. Can you assign to me please?

sure, go ahead

**Comment by jianajavier** [comment]
Here's the PR: https://github.com/SethWalkeroo/Quiet-Text/pull/79
