### ISSUE TITLE
Allow the user to indent blocks of code with the tab key. 

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#72]
Allow the user to select a chunk of text in the editor and hit tab to indent the entire block. Bonus points if you also implement a <kbd>shift</kbd>+<kbd>tab</kbd> command for unindenting the block of text.

**Comment by Guiguerreiro39** [comment]
Hi,
Can you assign it to me? I would like to take a look at this

**Comment by Guiguerreiro39** [comment]
Unfortunately I haven't implemented the bonus feature @SethWalkeroo but create another issue and I'll give it a look!
