### ISSUE TITLE
Add a CLI argument to launch the application with opening the specified file

### ISSUE THREAD

**Issue by sonnymilton** [SethWalkeroo/Quiet-Text#74]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't specify the name of the file that should be opened when starting the application from the command line.

**Describe the solution you'd like**
Add a command line argument that you can use to specify the name of the file to open.

**Describe alternatives you've considered**
\-

**Additional context**
I think the best option is to use the last argument as the file path.
`python3 quiet_app_launch.py /path/to/somefile.txt` command will be used to start application with opening somefile.txt.
The path can be relative (from the current directory) or absolute.

**Comment by sonnymilton** [comment]
Hello, @SethWalkeroo! Do you like this feature?
If you like the feature, then I could work on it. Can you assign this issue to me, please?

**Comment by SethWalkeroo** [comment]
@Sonny812 Sure, seems like a cool idea, especially since there is no binary release yet.
