### ISSUE TITLE
Allow users to unindent multiple lines of code with Shift and Tab

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#77]
Right now users can indent multiple lines using <kbd>Tab</kbd> but we also want them to be able to unindent multiple lines as well with <kbd>Shift</kbd>+<kbd>Tab</kbd>.

**Comment by Guiguerreiro39** [comment]
I'll happily do it!

**Comment by SethWalkeroo** [comment]
@Guiguerreiro39 Go ahead, round 2 :)

**Comment by SethWalkeroo** [comment]
@Guiguerreiro39 Hey I was wondering if I could get you to fix your auto unindent feature. I'm embarrassed to admit, but I didn't test it before I merged it, and it turns out it doesn't work. When you bound your tab_text function to the tab key, you overwrote the normal function of the tab key and now it doesn't work at all. deleted the keybindings and recommitted the branch for the time being.

**Comment by Guiguerreiro39** [comment]
> @Guiguerreiro39 Hey I was wondering if I could get you to fix your auto unindent feature. I'm embarrassed to admit, but I didn't test it before I merged it, and it turns out it doesn't work. When you bound your tab_text function to the tab key, you overwrote the normal function of the tab key and now it doesn't work at all. deleted the keybindings and recommitted the branch for the time being.

It's working for me in single and multi lines.. What OS are you using?

**Comment by SethWalkeroo** [comment]
@Guiguerreiro39 I am on Linux, maybe that's the issue?

**Comment by Guiguerreiro39** [comment]
> @Guiguerreiro39 I am on Linux, maybe that's the issue?

Yes, that's the issue :( I will fix it for linux as well

**Comment by Guiguerreiro39** [comment]
Since I'm not using linux and I don't really have the time to setup a VM with it, can you test with this keybind instead? @SethWalkeroo 

**<Shift-ISO_Left_Tab>** or **<Control-ISO_Left_Tab>**

**Comment by SethWalkeroo** [comment]
@Guiguerreiro39 Of course, one minute.

**Comment by SethWalkeroo** [comment]
@Guiguerreiro39 I'm still running into the same problem. I can't tab or indent anything.

**Comment by Guiguerreiro39** [comment]
@SethWalkeroo Are you getting any error in the console?

**Comment by SethWalkeroo** [comment]
@Guiguerreiro39 I am not getting any errors in the console, no.

**Comment by Guiguerreiro39** [comment]
Well that's annoying ... I will write some code that makes the keybind work only for mac or windows and then I can later figure out which keybind should I use for linux

**Comment by Guiguerreiro39** [comment]
@SethWalkeroo just a thought.. can you remove the keypress inside of the keybinds that I've made?

**Comment by SethWalkeroo** [comment]
@Guiguerreiro39 Still no luck. I have a Windows pc I can test this on. I'll check it out on there and see if I can't put a fix together.

**Comment by Guiguerreiro39** [comment]
Let me know once you can test it 👍

**Comment by SethWalkeroo** [comment]
@Guiguerreiro39 Hmm, I tested this on my Windows computer and it still wasn't working. Do you know anybody else that can try this out?

**Comment by Guiguerreiro39** [comment]
> @Guiguerreiro39 Hmm, I tested this on my Windows computer and it still wasn't working. Do you know anybody else that can try this out?

I don't know.. But it's weird, in mine is working perfectly.. I saw in the master branch the function is not up-to-date? Have you tested with the new one or did you test it just after cloning?

**Comment by Guiguerreiro39** [comment]
![Indent](https://user-images.githubusercontent.com/11543544/96112087-fec5cc80-0ed9-11eb-9a01-1a0142698e21.gif)

**Comment by SethWalkeroo** [comment]
@Guiguerreiro39 Is this using your version of the main branch? I will give it another go.

**Comment by Guiguerreiro39** [comment]
> @Guiguerreiro39 Is this using your version of the main branch? I will give it another go.

Yes, I've tested with my current version on my main branch.. I saw yours and it seems it's not up-to-date with mine, atleast the part for unindent

**Comment by SethWalkeroo** [comment]
@Guiguerreiro39 Yes, that's because I removed the bindings and code for the time being. I just tried your branch with windows and I am running into the same problem. Any other ideas for what the issue might be?

**Comment by Guiguerreiro39** [comment]
> @Guiguerreiro39 Yes, that's because I removed the bindings and code for the time being. I just tried your branch with windows and I am running into the same problem. Any other ideas for what the issue might be?

That's really weird.. The keybind function is the thing that's overwritting the normal functionality of <kbd>Tab</kbd> when returning "break", so I think your machine is recognizing the keypress.. Is indenting multiple lines working? If you had time to debug the function it would be great

**Comment by Guiguerreiro39** [comment]
> > @Guiguerreiro39 Yes, that's because I removed the bindings and code for the time being. I just tried your branch with windows and I am running into the same problem. Any other ideas for what the issue might be?
> 
> That's really weird.. The keybind function is the thing that's overwritting the normal functionality of Tab when returning "break", so I think your machine is recognizing the keypress.. Is indenting multiple lines working? If you had time to debug the function it would be great

Can it be python version? Mine is 3.8.3

**Comment by SethWalkeroo** [comment]
@Guiguerreiro39 I think that I am close to fixing things. It has to do with the event state, and the binding with shift and tab. I changed the if statements in the function to check for even.state == 0 instead of 8, and I swapped the keybinding shift-keypress-tab for control-i (for testing) and everything worked perfectly. I will let you know when I think everything works (for me at least) and then you can test it on your machine.

**Comment by Guiguerreiro39** [comment]
OK great! The event.state that I was getting for <kbd>Shift</kbd>+<kbd>Tab</kbd> was 8, it might change on different machines or versions perhaps! Looking forward for updates 👍

**Comment by SethWalkeroo** [comment]
@Guiguerreiro39 Okay, so things are working as expected, I can tab and untab text, but there seems to be another issue. I can only unindent text that I have indented in the current session. If I try to unindent  text that indented before I opened the file, it does nothing. Is this issue something else related to the current issue, or does this happen for you as well?

**Comment by Guiguerreiro39** [comment]
@SethWalkeroo Well, I've tried to write a file, indent, save and reopen and it's still working fine.. One thing to consider is that copied text from vscode seem to replace /t for spaces and the unindent does only delete /t characters at the beginning of the line.. That can be the cause of this issue
