### ISSUE TITLE
Create some more color schemes for the text editor. 

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#88]
The editor has 6 color schemes/themes at the time of writing this: Monokai, Monokai Pro, Solarized, Gruvbox, Dark Heart, and Githubly. It would be cool to see some other popular themes for the editor as well. The themes are made with .yaml files inside the theme directory. You can enable the themes yourself by creating functions for loading the themes inside quiet_menubar.py, but that is not required, and I can handle that afterwards if needed.

**Comment by JakubGacki** [comment]
Would you mind if I add a Dracula and Pumpkin theme?

**Comment by SethWalkeroo** [comment]
> Would you mind if I add a Dracula and Pumpkin theme?

of course not, more the merrier! I'll probably have to find a better way to store and organize themes, but add whatever you like for now.

**Comment by JakubGacki** [comment]
Great!

I already add a [proposal](https://github.com/SethWalkeroo/Quiet-Text/issues/91) of a little change in **quiet_menubar.py**. It could be a good start of themes management improvement.

**Comment by JakubGacki** [comment]
Do you have restricted access to the repository?

**Comment by SethWalkeroo** [comment]
@JakubGacki No, what are you talking about?

**Comment by JakubGacki** [comment]
@SethWalkeroo I've got error that permission to this repo is denied to me.

**Comment by SethWalkeroo** [comment]
> @SethWalkeroo I've got error that permission to this repo is denied to me.

Did you get this figured out? Seems like you got the repository and a pull request out okay.
