### ISSUE TITLE
Allow users to compile and run C files with the ctrl+r run command on Windows

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#89]
Right now you can compile and run C files, but it only works with the gnome terminal on Linux. it would be great to have this work on Windows as well.

**Comment by rudhrasekar** [comment]
I would like to work on this, Can you assign me the issue?

**Comment by SethWalkeroo** [comment]
@rudhrasekar sure, go for it!
