### ISSUE TITLE
Add functionality to the right click popup menu

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#9]
Right now we have a right click popup menu with three options: cut, copy, paste. None of these options actually do anything at the moment and that sucks. The goal is to add functionality to these popup options.

**Comment by AyonPal** [comment]
I would really love to work on that issue

**Comment by SethWalkeroo** [comment]
@AyonPal Sure, go for it! Assigned the issue for you. Message me if you have any issues.

**Comment by hrishikesharma** [comment]
I have solved this.  

Can I open a pull request?

**Comment by SethWalkeroo** [comment]
@hrishikesharma Sure
