### ISSUE TITLE
start.bat and start.sh tries to open a non-existing file

### ISSUE THREAD

**Issue by PointThink** [SethWalkeroo/Quiet-Text#95]
the start.bat and star.sh scripts try to open _quiet_app_launch.py_ which is a file that doesn't exist

start.bat
`python3 quiet_app_launch.py`

start.sh
`#!/bin/sh`
`/usr/bin/env`` python3 quiet_app_launch.py`

**Comment by PointThink** [comment]
should be a quick fix

**Comment by SethWalkeroo** [comment]
@pointThink Ah, thank you! I changed the main file a while back and forgot to change this.
